# Schema for the configuration files of the Config Entity Example module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/config_entity_example.robot.marvin.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

config_continent_entity.continent.*:
  type: config_entity
  label: 'Continent'
  mapping:
    id:
      type: string
      label: 'Continent id'
    machine_name:
      type: string
      label: 'Machine Name'
    name:
      type: string
      label: 'Name'
    code:
      type: string
      label: 'Code'

config_continent_entity.country.*:
  type: config_entity
  label: 'Country'
  mapping:
    id:
      type: string
      label: 'Country id'
    machine_name:
      type: string
      label: 'Machine Name'
    name:
      type: string
      label: 'Name'
    code:
      type: string
      label: 'Code'
    continent_id:
      type: string
      label: 'Continent Machine Name'
